#!/usr/bin/env node

/**
 * Build script to inject environment variables into Chrome extension files
 */

const fs = require('fs');
const path = require('path');
require('dotenv').config();

/**
 * Replace environment variables in manifest.json
 */
function buildManifest() {
  const manifestTemplate = {
    "manifest_version": 3,
    "name": process.env.EXTENSION_NAME || "Gmail API Email Sender",
    "version": process.env.EXTENSION_VERSION || "3.0",
    "description": process.env.EXTENSION_DESCRIPTION || "Send emails directly via Gmail API with attachments",
    "permissions": [
      "activeTab",
      "storage",
      "identity"
    ],
    "host_permissions": [
      "https://www.googleapis.com/*"
    ],
    "action": {
      "default_popup": "popup.html",
      "default_title": process.env.EXTENSION_NAME || "Gmail API Email Sender"
    },
    "oauth2": {
      "client_id": process.env.GOOGLE_CLIENT_ID || "",
      "scopes": [
        "https://www.googleapis.com/auth/gmail.send"
      ]
    }
  };

  // Validate required environment variables
  if (!process.env.GOOGLE_CLIENT_ID) {
    console.error('Error: GOOGLE_CLIENT_ID is required in .env file');
    process.exit(1);
  }

  fs.writeFileSync('manifest.json', JSON.stringify(manifestTemplate, null, 2));
  console.log('✅ manifest.json generated with environment variables');
}

/**
 * Create a config file with environment variables for the extension
 */
function buildConfig() {
  const configContent = `
// Auto-generated configuration from environment variables
// Do not edit this file directly - edit .env instead

window.ENV_CONFIG = {
  GOOGLE_CLIENT_ID: "${process.env.GOOGLE_CLIENT_ID || ''}",
  EXTENSION_NAME: "${process.env.EXTENSION_NAME || 'Gmail API Email Sender'}",
  EXTENSION_VERSION: "${process.env.EXTENSION_VERSION || '3.0'}",
  DEFAULT_EMAIL_SUBJECT: "${process.env.DEFAULT_EMAIL_SUBJECT || 'Android Developer Position'}",
  DEFAULT_SENDER_NAME: "${process.env.DEFAULT_SENDER_NAME || ''}",
  DEFAULT_SENDER_PHONE: "${process.env.DEFAULT_SENDER_PHONE || ''}"
};
`;

  fs.writeFileSync('config.js', configContent);
  console.log('✅ config.js generated with environment variables');
}

/**
 * Process HTML files for Chrome extension
 */
function processHtmlFiles() {
  // Process HTML files (keep src/ paths but make them work from root)
  processHtmlFile('src/popup/popup.html', 'popup.html');
  processHtmlFile('src/settings/settings.html', 'settings.html');
  
  console.log('✅ HTML files processed for Chrome extension');
}



/**
 * Process HTML file - keep src/ structure but update paths for root loading
 */
function processHtmlFile(srcPath, destPath) {
  if (!fs.existsSync(srcPath)) return;
  
  let content = fs.readFileSync(srcPath, 'utf8');
  
  // Keep src/ structure - just remove the ../ since we're loading from root
  content = content.replace(/src="\.\.\//g, 'src="src/');
  content = content.replace(/href="\.\.\//g, 'href="src/');
  
  // Fix config.js path (it's generated in root, not src/)
  content = content.replace(/src="src\/config\.js"/g, 'src="config.js"');
  
  // Update local file references to src/
  content = content.replace(/href="popup\.css"/g, 'href="src/popup/popup.css"');
  content = content.replace(/href="settings\.css"/g, 'href="src/settings/settings.css"');
  content = content.replace(/src="popup\.js"/g, 'src="src/popup/popup.js"');
  content = content.replace(/src="settings\.js"/g, 'src="src/settings/settings.js"');
  
  fs.writeFileSync(destPath, content);
}

/**
 * Main build function
 */
function build() {
  console.log('🔨 Building Chrome extension with environment variables...');
  
  try {
    buildManifest();
    buildConfig();
    processHtmlFiles();
    console.log('✅ Build completed successfully!');
  } catch (error) {
    console.error('❌ Build failed:', error.message);
    process.exit(1);
  }
}

// Run build if this script is executed directly
if (require.main === module) {
  build();
}

module.exports = { build, buildManifest, buildConfig };