#!/usr/bin/env node

/**
 * Build script to inject environment variables into Chrome extension files
 */

const fs = require('fs');
const path = require('path');
require('dotenv').config();

/**
 * Replace environment variables in manifest.json
 */
function buildManifest() {
  const manifestTemplate = {
    "manifest_version": 3,
    "name": process.env.EXTENSION_NAME || "Gmail API Email Sender",
    "version": process.env.EXTENSION_VERSION || "3.0",
    "description": process.env.EXTENSION_DESCRIPTION || "Send emails directly via Gmail API with attachments",
    "permissions": [
      "activeTab",
      "storage",
      "identity"
    ],
    "host_permissions": [
      "https://www.googleapis.com/*"
    ],
    "action": {
      "default_popup": "popup.html",
      "default_title": process.env.EXTENSION_NAME || "Gmail API Email Sender"
    },
    "oauth2": {
      "client_id": process.env.GOOGLE_CLIENT_ID || "",
      "scopes": [
        "https://www.googleapis.com/auth/gmail.send"
      ]
    }
  };

  // Validate required environment variables
  if (!process.env.GOOGLE_CLIENT_ID) {
    console.error('Error: GOOGLE_CLIENT_ID is required in .env file');
    process.exit(1);
  }

  fs.writeFileSync('manifest.json', JSON.stringify(manifestTemplate, null, 2));
  console.log('✅ manifest.json generated with environment variables');
}

/**
 * Create a config file with environment variables for the extension
 */
function buildConfig() {
  const configContent = `
// Auto-generated configuration from environment variables
// Do not edit this file directly - edit .env instead

window.ENV_CONFIG = {
  GOOGLE_CLIENT_ID: "${process.env.GOOGLE_CLIENT_ID || ''}",
  EXTENSION_NAME: "${process.env.EXTENSION_NAME || 'Gmail API Email Sender'}",
  EXTENSION_VERSION: "${process.env.EXTENSION_VERSION || '3.0'}",
  DEFAULT_EMAIL_SUBJECT: "${process.env.DEFAULT_EMAIL_SUBJECT || 'Android Developer Position'}",
  DEFAULT_SENDER_NAME: "${process.env.DEFAULT_SENDER_NAME || ''}",
  DEFAULT_SENDER_PHONE: "${process.env.DEFAULT_SENDER_PHONE || ''}"
};
`;

  fs.writeFileSync('config.js', configContent);
  console.log('✅ config.js generated with environment variables');
}

/**
 * Copy and process files for Chrome extension
 */
function copyFiles() {
  // Create directories if they don't exist
  const dirs = ['config', 'utils', 'services'];
  dirs.forEach(dir => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  });

  // Copy JavaScript files
  copyDirectory('src/config', 'config');
  copyDirectory('src/utils', 'utils');
  copyDirectory('src/services', 'services');

  // Copy CSS files
  if (fs.existsSync('src/popup/popup.css')) {
    fs.copyFileSync('src/popup/popup.css', 'popup.css');
  }
  if (fs.existsSync('src/settings/settings.css')) {
    fs.copyFileSync('src/settings/settings.css', 'settings.css');
  }

  // Copy and process HTML files (update script paths)
  processHtmlFile('src/popup/popup.html', 'popup.html');
  processHtmlFile('src/settings/settings.html', 'settings.html');

  // Copy JavaScript controllers
  if (fs.existsSync('src/popup/popup.js')) {
    fs.copyFileSync('src/popup/popup.js', 'popup.js');
  }
  if (fs.existsSync('src/settings/settings.js')) {
    fs.copyFileSync('src/settings/settings.js', 'settings.js');
  }
  
  console.log('✅ Files copied and processed for Chrome extension');
}

/**
 * Copy directory recursively
 */
function copyDirectory(src, dest) {
  if (!fs.existsSync(src)) return;
  
  if (!fs.existsSync(dest)) {
    fs.mkdirSync(dest, { recursive: true });
  }

  const files = fs.readdirSync(src);
  files.forEach(file => {
    const srcPath = path.join(src, file);
    const destPath = path.join(dest, file);
    
    if (fs.statSync(srcPath).isDirectory()) {
      copyDirectory(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  });
}

/**
 * Process HTML file and update script paths
 */
function processHtmlFile(srcPath, destPath) {
  if (!fs.existsSync(srcPath)) return;
  
  let content = fs.readFileSync(srcPath, 'utf8');
  
  // Update script paths from relative to absolute
  content = content.replace(/src="\.\.\//g, 'src="');
  content = content.replace(/href="\.\.\//g, 'href="');
  
  // Update CSS paths
  content = content.replace(/href="([^"]+)\.css"/g, 'href="$1.css"');
  
  fs.writeFileSync(destPath, content);
}

/**
 * Main build function
 */
function build() {
  console.log('🔨 Building Chrome extension with environment variables...');
  
  try {
    buildManifest();
    buildConfig();
    copyFiles();
    console.log('✅ Build completed successfully!');
  } catch (error) {
    console.error('❌ Build failed:', error.message);
    process.exit(1);
  }
}

// Run build if this script is executed directly
if (require.main === module) {
  build();
}

module.exports = { build, buildManifest, buildConfig };